### ISSUE TITLE
Bug: DateTimes are not inserted into the database correctly

### ISSUE THREAD

**Issue by Du-z** [ProphetLamb/Surreal.Net#37]
Continuation of #25 

Datetimes still are inserted with the fraction portion of the date prepended with two zeros. Tests seem to work as expected, despite the data being wrong.

![image](https://user-images.githubusercontent.com/16366766/191486533-1f79466c-19fa-449b-925d-0f2b39c9188e.png)

**Comment by ProphetLamb** [comment]
Thanks for the report, I've read the discussion on discord about this bug.

I reviewed the current implementation and found the following issues in addition to your report:
1. The current implementation for `DateTime` is entirely based on serializing a `DateOnly` followed by a `TimeOnly`. 
2. All `DateTime` and `DateTimeOffset` instances are converted to `UTC` (`Z` suffix) serializing a specific timezone (`+02` or `-06`) is not supported.
3. The serializer cannot handle integers represented in variable length, e.g. `4` instead of `04`.

**Comment by StephenGilboy** [comment]
This should be fixed in SurrealDB now. https://github.com/surrealdb/surrealdb/issues/250

**Comment by ProphetLamb** [comment]
True, sadly, the changeset is not in the current beta release.
We could change our CI to compile SurrealDB from source, but that doesn't represent the average user. So we'll have to wait with the issue, until the next surrealdb release :(

@tobiemh do you have any information on the release schedule of SurrealDB? Is there a high velocity release channel, something like nightly/weekly, in the works?

**Comment by Du-z** [comment]
We can this bug open (tagged as blocked maybe?) and keep the tests commented. When the the update rolls out we can un-comment them and close this issue.

**Comment by ProphetLamb** [comment]
Blocked until https://github.com/surrealdb/surrealdb/issues/250 is in release

**Comment by tobiemh** [comment]
Hi @ProphetLamb , I've added a nightly release so that the main branch is released daily. This should be going live midnight tonight UTC time!

**Comment by ProphetLamb** [comment]
Neat! Thanks a lot, makes developing much easier.

**Comment by ProphetLamb** [comment]
Solved with #52
